Question 4: 
Constructing matrices, computing the Inverse and determinant  of a matrix, 
Decompose the matrix and transform the matrix

In [1]:
import numpy as np

Given the matrix below;


In [2]:
matrix = np.array([[1, 0.2, 0.5],
                   [0.2, 1, 0.8],
                   [0.5, 0.8, 1]])

(a) Inversion of matrix(Transponse)

In [3]:
 
matrix_A=np.array([[1,0.2,0.5],
                 [0.2,1,0.8],
                 [0.5,0.8,1]])


Compute the inverse of the matrix



In [4]:
inverse_matrix_A = np.linalg.inv(matrix)

In [5]:
print(inverse_matrix_A)

[[ 1.56521739  0.86956522 -1.47826087]
 [ 0.86956522  3.26086957 -3.04347826]
 [-1.47826087 -3.04347826  4.17391304]]


(b) Computing the determinant of matrix A

In [6]:
matrix_A=np.array([[1,0.2,0.5],
                 [0.2,1,0.8],
                 [0.5,0.8,1]])

Computing determinant of Matrix A

In [8]:
det_matrix_A=np.linalg.det(matrix_A)

Printing the result

In [9]:
print(det_matrix_A)

0.2299999999999999


In [10]:
print(f"The determinant of matrix1 is {det_matrix_A}")

The determinant of matrix1 is 0.2299999999999999


(c) Decomposing the matrix

eigenvalues, eigenvectors = np.linalg.eig(matrix)
print("(c) Eigenvalues:\n", eigenvalues)
print("    Eigenvectors:\n", eigenvectors)

Given Matrix A

In [16]:
matrix_A = np.array([[1, 0.2, 0.5],
                   [0.2, 1, 0.8],
                   [0.5, 0.8, 1]])

In [17]:
eigenvalues, eigenvectors = np.linalg.eig(matrix)

In [19]:
print(eigenvalues)


[2.04100779 0.82188052 0.13711169]


In [20]:
print(eigenvectors)

[[-0.43721717 -0.85359707 -0.28321933]
 [-0.59931898  0.51133314 -0.61591816]
 [-0.67056536  0.09955128  0.73514055]]


(d)Transform the matrix 

In [11]:
transformation_matrix_A = np.array([[2, 0, 0],
                                  [0, 3, 0],
                                  [0, 0, 1]])

In [14]:
transformed_matrix_A = matrix.dot(transformation_matrix_A)

Printing the transformed matrix of A

In [15]:
print(transformed_matrix_A)

[[2.  0.6 0.5]
 [0.4 3.  0.8]
 [1.  2.4 1. ]]
